using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using VitaCernita.Core.Actions;
using VitaCernita.Core.AutoReply;
using VitaCernita.Core.Filters;
using VitaCernita.Core.Labels;
using VitaCernita.Core.Queries;
using VitaCernita.Core.Sources;

namespace VitaCernita.Core.Serialization;

/// <summary>
/// Serializes queryable Gmail mailbox configurations (labels, filters, and auto-reply vacation settings)
/// into Lua configuration scripts using the primary Functional DSL syntax.
/// Supports bidirectional round-trip evaluation where serialized Lua re-parses into identical configurations.
/// </summary>
public class LuaConfigSerializer
{
    private const string DefaultHeader =
@"-- =======================================================================
-- Generated by VitaCernita Lua Config Serializer
-- =======================================================================";

    /// <summary>
    /// Shared default serializer instance.
    /// </summary>
    public static LuaConfigSerializer Default { get; } = new();

    // =========================================================================
    // 1. IGmailSource Serialization (diffing interface integration)
    // =========================================================================

    /// <summary>
    /// Serializes all configuration items from an abstract <see cref="IGmailSource"/> into a Functional DSL Lua script.
    /// </summary>
    public async Task<string> SerializeAsync(
        IGmailSource source,
        LuaSerializerOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        if (source == null) throw new ArgumentNullException(nameof(source));
        options ??= new LuaSerializerOptions();

        var labels = await source.GetLabelsAsync(cancellationToken);
        var filters = await source.GetFiltersAsync(cancellationToken);
        var autoReply = await source.GetAutoReplyAsync(cancellationToken);

        return Serialize(labels, filters, autoReply, options);
    }

    /// <summary>
    /// Serializes all configuration items from an abstract <see cref="IGmailSource"/> to a Lua file.
    /// </summary>
    public async Task SerializeToFileAsync(
        IGmailSource source,
        string filePath,
        LuaSerializerOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(filePath)) throw new ArgumentNullException(nameof(filePath));
        string lua = await SerializeAsync(source, options, cancellationToken);

        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }
        await File.WriteAllTextAsync(filePath, lua, cancellationToken);
    }

    // =========================================================================
    // 2. Collection Serialization (IQueryable & IEnumerable)
    // =========================================================================

    /// <summary>
    /// Serializes queryable collections of labels, filters, and optional auto-reply settings into a unified Lua script.
    /// </summary>
    public string Serialize(
        IQueryable<GmailLabel>? labels,
        IQueryable<GmailFilter>? filters,
        AutoReply.AutoReply? autoReply = null,
        LuaSerializerOptions? options = null) =>
        Serialize((IEnumerable<GmailLabel>?)labels, (IEnumerable<GmailFilter>?)filters, autoReply, options);

    /// <summary>
    /// Serializes enumerable collections of labels, filters, and optional auto-reply settings into a unified Lua script.
    /// </summary>
    public string Serialize(
        IEnumerable<GmailLabel>? labels,
        IEnumerable<GmailFilter>? filters,
        AutoReply.AutoReply? autoReply = null,
        LuaSerializerOptions? options = null)
    {
        options ??= new LuaSerializerOptions();
        var sb = new StringBuilder();

        AppendHeader(sb, options);

        var labelList = labels?.ToList() ?? new List<GmailLabel>();
        var filterList = filters?.ToList() ?? new List<GmailFilter>();

        bool hasLabels = labelList.Count > 0 || !options.OmitEmptySections && labels != null;
        bool hasFilters = filterList.Count > 0 || !options.OmitEmptySections && filters != null;
        bool hasAutoReply = autoReply != null;

        if (!hasLabels && !hasFilters && !hasAutoReply)
        {
            sb.AppendLine("return {}");
            return sb.ToString();
        }

        sb.AppendLine("return {");

        var sections = new List<string>();

        if (hasLabels)
        {
            sections.Add(FormatLabelsSection(labelList, indentLevel: 1, options));
        }

        if (hasFilters)
        {
            sections.Add(FormatFiltersSection(filterList, indentLevel: 1, options, labelList));
        }

        if (hasAutoReply && autoReply != null)
        {
            sections.Add(FormatAutoReplySection(autoReply, indentLevel: 1, options));
        }

        sb.AppendLine(string.Join(",\n\n", sections));
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Serializes collections to a file synchronously.
    /// </summary>
    public void SerializeToFile(
        string filePath,
        IEnumerable<GmailLabel>? labels,
        IEnumerable<GmailFilter>? filters,
        AutoReply.AutoReply? autoReply = null,
        LuaSerializerOptions? options = null)
    {
        if (string.IsNullOrWhiteSpace(filePath)) throw new ArgumentNullException(nameof(filePath));
        string lua = Serialize(labels, filters, autoReply, options);

        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }
        File.WriteAllText(filePath, lua);
    }

    // =========================================================================
    // 3. Granular Collection Serializers
    // =========================================================================

    /// <summary>
    /// Serializes a collection of labels into a standalone Lua configuration script ({ labels = { ... } }).
    /// </summary>
    public string SerializeLabels(IEnumerable<GmailLabel> labels, LuaSerializerOptions? options = null)
    {
        if (labels == null) throw new ArgumentNullException(nameof(labels));
        return Serialize(labels, filters: null, autoReply: null, options);
    }

    /// <summary>
    /// Serializes a collection of filters into a standalone Lua configuration script ({ filters = { ... } }).
    /// </summary>
    public string SerializeFilters(IEnumerable<GmailFilter> filters, LuaSerializerOptions? options = null)
    {
        if (filters == null) throw new ArgumentNullException(nameof(filters));
        return Serialize(labels: null, filters, autoReply: null, options);
    }

    /// <summary>
    /// Serializes auto-reply vacation settings into a standalone Lua configuration script ({ auto_reply = ... }).
    /// </summary>
    public string SerializeAutoReply(AutoReply.AutoReply autoReply, LuaSerializerOptions? options = null)
    {
        if (autoReply == null) throw new ArgumentNullException(nameof(autoReply));
        return Serialize(labels: null, filters: null, autoReply, options);
    }

    // =========================================================================
    // 4. Single Entity Serializers
    // =========================================================================

    /// <summary>
    /// Serializes a single label definition into a Functional DSL script (`return label { ... }`).
    /// </summary>
    public string SerializeLabel(GmailLabel label, LuaSerializerOptions? options = null)
    {
        if (label == null) throw new ArgumentNullException(nameof(label));
        options ??= new LuaSerializerOptions();

        var sb = new StringBuilder();
        AppendHeader(sb, options);
        sb.AppendLine($"return {FormatLabelBlock(label, indentLevel: 0, options)}");
        return sb.ToString();
    }

    /// <summary>
    /// Serializes a single filter definition into a Functional DSL script (`return filter { ... }`).
    /// </summary>
    public string SerializeFilter(GmailFilter filter, LuaSerializerOptions? options = null, IEnumerable<GmailLabel>? knownLabels = null)
    {
        if (filter == null) throw new ArgumentNullException(nameof(filter));
        options ??= new LuaSerializerOptions();

        var sb = new StringBuilder();
        AppendHeader(sb, options);
        sb.AppendLine($"return {FormatFilterBlock(filter, indentLevel: 0, options, knownLabels)}");
        return sb.ToString();
    }

    // =========================================================================
    // 5. Query Condition & Action Serializers
    // =========================================================================

    /// <summary>
    /// Serializes an individual query condition expression into Functional DSL syntax.
    /// </summary>
    public string SerializeQueryCondition(IQueryCondition condition, int indentLevel = 0, LuaSerializerOptions? options = null)
    {
        if (condition == null) throw new ArgumentNullException(nameof(condition));
        options ??= new LuaSerializerOptions();
        return FormatCondition(condition, indentLevel, options);
    }

    /// <summary>
    /// Serializes an individual action definition into Functional DSL syntax (`actions(...)`).
    /// </summary>
    public string SerializeAction(GmailAction action, LuaSerializerOptions? options = null, IEnumerable<GmailLabel>? knownLabels = null)
    {
        if (action == null) throw new ArgumentNullException(nameof(action));
        options ??= new LuaSerializerOptions();
        return FormatAction(action, options, knownLabels);
    }

    // =========================================================================
    // Private Formatting Helpers
    // =========================================================================

    private static void AppendHeader(StringBuilder sb, LuaSerializerOptions options)
    {
        if (!options.IncludeHeaderComment) return;

        string header = options.HeaderComment ?? DefaultHeader;
        sb.AppendLine(header);
        sb.AppendLine();
    }

    private static string FormatLabelsSection(IReadOnlyList<GmailLabel> labels, int indentLevel, LuaSerializerOptions options)
    {
        var indent = Indent(indentLevel, options);
        if (labels.Count == 0)
        {
            return $"{indent}labels = {{}}";
        }

        var blocks = labels.Select(l => FormatLabelBlock(l, indentLevel + 1, options));
        return $"{indent}labels = {{\n{string.Join(",\n", blocks)}\n{indent}}}";
    }

    private static string FormatFiltersSection(
        IReadOnlyList<GmailFilter> filters,
        int indentLevel,
        LuaSerializerOptions options,
        IEnumerable<GmailLabel>? knownLabels = null)
    {
        var indent = Indent(indentLevel, options);
        if (filters.Count == 0)
        {
            return $"{indent}filters = {{}}";
        }

        var blocks = filters.Select(f => FormatFilterBlock(f, indentLevel + 1, options, knownLabels));
        return $"{indent}filters = {{\n{string.Join(",\n", blocks)}\n{indent}}}";
    }

    private static string FormatAutoReplySection(AutoReply.AutoReply autoReply, int indentLevel, LuaSerializerOptions options)
    {
        var indent = Indent(indentLevel, options);
        string block = FormatAutoReplyBlock(autoReply, indentLevel, options);
        return $"{indent}auto_reply = {block.TrimStart()}";
    }

    public static string FormatLabelBlock(GmailLabel label, int indentLevel, LuaSerializerOptions options)
    {
        var indent = Indent(indentLevel, options);
        var childIndent = Indent(indentLevel + 1, options);
        var lines = new List<string>();

        if (!string.IsNullOrWhiteSpace(label.Id))
        {
            lines.Add($"{childIndent}id = \"{EscapeLuaString(label.Id)}\"");
        }

        lines.Add($"{childIndent}name = \"{EscapeLuaString(label.Name)}\"");

        if (!string.IsNullOrWhiteSpace(label.MessageListVisibility))
        {
            lines.Add($"{childIndent}message_list_visibility = \"{EscapeLuaString(label.MessageListVisibility)}\"");
        }

        if (!string.IsNullOrWhiteSpace(label.LabelListVisibility))
        {
            lines.Add($"{childIndent}label_list_visibility = \"{EscapeLuaString(label.LabelListVisibility)}\"");
        }

        if (label.Color != null)
        {
            string text = FormatColor(label.Color.TextColor, options);
            string bg = FormatColor(label.Color.BackgroundColor, options);
            lines.Add($"{childIndent}color = color({text}, {bg})");
        }

        return $"{indent}label {{\n{string.Join(",\n", lines)}\n{indent}}}";
    }

    public static string FormatFilterBlock(
        GmailFilter filter,
        int indentLevel,
        LuaSerializerOptions options,
        IEnumerable<GmailLabel>? knownLabels = null)
    {
        var indent = Indent(indentLevel, options);
        var childIndent = Indent(indentLevel + 1, options);
        var lines = new List<string>();

        if (!string.IsNullOrWhiteSpace(filter.Id))
        {
            lines.Add($"{childIndent}id = \"{EscapeLuaString(filter.Id)}\"");
        }

        if (!string.IsNullOrWhiteSpace(filter.Name))
        {
            lines.Add($"{childIndent}name = \"{EscapeLuaString(filter.Name)}\"");
        }

        if (filter.Query != null)
        {
            string queryStr = FormatCondition(filter.Query, indentLevel + 1, options);
            lines.Add($"{childIndent}query = {queryStr}");
        }

        if (filter.Action != null && !filter.Action.IsEmpty)
        {
            string actionStr = FormatAction(filter.Action, options, knownLabels);
            lines.Add($"{childIndent}action = {actionStr}");
        }

        return $"{indent}filter {{\n{string.Join(",\n", lines)}\n{indent}}}";
    }

    public static string FormatAutoReplyBlock(AutoReply.AutoReply autoReply, int indentLevel, LuaSerializerOptions options)
    {
        var indent = Indent(indentLevel, options);
        var childIndent = Indent(indentLevel + 1, options);
        var lines = new List<string>();

        lines.Add($"{childIndent}enabled = {(autoReply.EnableAutoReply ? "true" : "false")}");

        if (!string.IsNullOrWhiteSpace(autoReply.ResponseSubject))
        {
            lines.Add($"{childIndent}subject = \"{EscapeLuaString(autoReply.ResponseSubject)}\"");
        }

        if (!string.IsNullOrWhiteSpace(autoReply.ResponseBodyPlainText))
        {
            lines.Add($"{childIndent}body = \"{EscapeLuaString(autoReply.ResponseBodyPlainText)}\"");
        }

        if (!string.IsNullOrWhiteSpace(autoReply.ResponseBodyHtml))
        {
            lines.Add($"{childIndent}html = \"{EscapeLuaString(autoReply.ResponseBodyHtml)}\"");
        }

        if (autoReply.RestrictToContacts || !options.OmitDefaultValues)
        {
            lines.Add($"{childIndent}contacts_only = {(autoReply.RestrictToContacts ? "true" : "false")}");
        }

        if (autoReply.RestrictToDomain || !options.OmitDefaultValues)
        {
            lines.Add($"{childIndent}domain_only = {(autoReply.RestrictToDomain ? "true" : "false")}");
        }

        if (autoReply.StartTime.HasValue)
        {
            var dto = DateTimeOffset.FromUnixTimeMilliseconds(autoReply.StartTime.Value);
            if (dto.TimeOfDay == TimeSpan.Zero)
            {
                lines.Add($"{childIndent}start_date = \"{dto:yyyy-MM-dd}\"");
            }
            else if (dto.Millisecond == 0)
            {
                lines.Add($"{childIndent}start_time = \"{dto:yyyy-MM-ddTHH:mm:ssZ}\"");
            }
            else
            {
                lines.Add($"{childIndent}start_time = \"{dto:yyyy-MM-ddTHH:mm:ss.fffZ}\"");
            }
        }

        if (autoReply.EndTime.HasValue)
        {
            var dto = DateTimeOffset.FromUnixTimeMilliseconds(autoReply.EndTime.Value);
            if (dto.TimeOfDay == TimeSpan.Zero)
            {
                lines.Add($"{childIndent}end_date = \"{dto:yyyy-MM-dd}\"");
            }
            else if (dto.Millisecond == 0)
            {
                lines.Add($"{childIndent}end_time = \"{dto:yyyy-MM-ddTHH:mm:ssZ}\"");
            }
            else
            {
                lines.Add($"{childIndent}end_time = \"{dto:yyyy-MM-ddTHH:mm:ss.fffZ}\"");
            }
        }

        return $"{indent}auto_reply {{\n{string.Join(",\n", lines)}\n{indent}}}";
    }

    public static string FormatCondition(IQueryCondition condition, int indentLevel, LuaSerializerOptions options)
    {
        return condition switch
        {
            FieldCondition fc => FormatFieldCondition(fc),
            HasCondition hc => FormatHasCondition(hc),
            IsCondition ic => FormatIsCondition(ic),
            InCondition inc => FormatInCondition(inc),
            CategoryCondition cc => FormatCategoryCondition(cc),
            SizeCondition sc => FormatSizeCondition(sc),
            DateCondition dc => FormatDateCondition(dc),
            DurationCondition durc => FormatDurationCondition(durc),
            ExactMatchCondition emc => $"match(\"{EscapeLuaString(emc.Phrase)}\")",
            RawQueryCondition rqc => $"raw_query(\"{EscapeLuaString(rqc.Query)}\")",
            NotCondition nc => $"Not({FormatCondition(nc.InnerCondition, indentLevel, options)})",
            AndCondition ac => FormatAndCondition(ac, indentLevel, options),
            OrCondition oc => FormatOrCondition(oc, indentLevel, options),
            _ => $"query(\"{EscapeLuaString(condition.ToGmailQuery())}\")"
        };
    }

    private static string FormatFieldCondition(FieldCondition fc)
    {
        string escaped = EscapeLuaString(fc.Value);
        return fc.Field.ToLowerInvariant() switch
        {
            "from" => $"From(\"{escaped}\")",
            "to" => $"To(\"{escaped}\")",
            "cc" => $"Cc(\"{escaped}\")",
            "bcc" => $"Bcc(\"{escaped}\")",
            "subject" => $"Subject(\"{escaped}\")",
            "list" => $"List(\"{escaped}\")",
            "filename" => $"Filename(\"{escaped}\")",
            "deliveredto" => $"delivered_to(\"{escaped}\")",
            "rfc822msgid" => $"rfc822msgid(\"{escaped}\")",
            "header" => $"Header(\"{escaped}\")",
            "label" => $"label(\"{escaped}\")",
            "after" => $"After(\"{escaped}\")",
            "before" => $"Before(\"{escaped}\")",
            "older" => $"Older(\"{escaped}\")",
            "newer" => $"Newer(\"{escaped}\")",
            "older_than" => $"older_than(\"{escaped}\")",
            "newer_than" => $"newer_than(\"{escaped}\")",
            _ => $"{fc.Field}(\"{escaped}\")"
        };
    }

    private static string FormatHasCondition(HasCondition hc)
    {
        return hc.Target.ToLowerInvariant() switch
        {
            "yellow-star" => "has_yellow_star",
            "orange-star" => "has_orange_star",
            "red-star" => "has_red_star",
            "purple-star" => "has_purple_star",
            "blue-star" => "has_blue_star",
            "green-star" => "has_green_star",
            "red-bang" => "has_red_bang",
            "yellow-bang" => "has_yellow_bang",
            "orange-guillemet" => "has_orange_guillemet",
            "green-check" => "has_green_check",
            "blue-info" => "has_blue_info",
            "purple-question" => "has_purple_question",
            "attachment" => "has_attachment",
            "drive" => "has_drive",
            "document" => "has_document",
            "spreadsheet" => "has_spreadsheet",
            "presentation" => "has_presentation",
            "youtube" => "has_youtube",
            "userlabels" => "has_user_labels",
            "nouserlabels" => "has_no_user_labels",
            _ => $"has(\"{EscapeLuaString(hc.Target)}\")"
        };
    }

    private static string FormatIsCondition(IsCondition ic)
    {
        return ic.Target.ToLowerInvariant() switch
        {
            "starred" => "is_starred",
            "unread" => "is_unread",
            "read" => "is_read",
            "important" => "is_important",
            "muted" => "is_muted",
            "snoozed" => "is_snoozed",
            "chat" => "is_chat",
            "draft" => "is_draft",
            "sent" => "is_sent",
            "trash" => "is_trash",
            "spam" => "is_spam",
            _ => $"is(\"{EscapeLuaString(ic.Target)}\")"
        };
    }

    private static string FormatInCondition(InCondition inc)
    {
        return inc.Target.ToLowerInvariant() switch
        {
            "anywhere" => "in_anywhere",
            "archive" => "in_archive",
            "snoozed" => "in_snoozed",
            "inbox" => "in_inbox",
            "sent" => "in_sent",
            "drafts" => "in_drafts",
            "trash" => "in_trash",
            "spam" => "in_spam",
            "chats" => "in_chats",
            _ => $"In(\"{EscapeLuaString(inc.Target)}\")"
        };
    }

    private static string FormatCategoryCondition(CategoryCondition cc)
    {
        return cc.Target.ToLowerInvariant() switch
        {
            "primary" or "personal" => "category_primary",
            "social" => "category_social",
            "promotions" or "promotion" => "category_promotions",
            "updates" or "update" => "category_updates",
            "forums" or "forum" => "category_forums",
            "reservations" or "reservation" => "category_reservations",
            "purchases" or "purchase" => "category_purchases",
            _ => $"category(\"{EscapeLuaString(cc.Target)}\")"
        };
    }

    private static string FormatSizeCondition(SizeCondition sc)
    {
        string escaped = EscapeLuaString(sc.Size);
        return sc.Operator.ToLowerInvariant() switch
        {
            "larger" or "larger_than" => $"larger(\"{escaped}\")",
            "smaller" or "smaller_than" => $"smaller(\"{escaped}\")",
            _ => $"size(\"{escaped}\")"
        };
    }

    private static string FormatDateCondition(DateCondition dc)
    {
        string d = dc.Date.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture);
        return dc.Operator.ToLowerInvariant() switch
        {
            "after" => $"After(\"{d}\")",
            "before" => $"Before(\"{d}\")",
            "older" => $"Older(\"{d}\")",
            "newer" => $"Newer(\"{d}\")",
            _ => $"{dc.Operator}(\"{d}\")"
        };
    }

    private static string FormatDurationCondition(DurationCondition durc)
    {
        string escaped = EscapeLuaString(durc.Duration);
        return durc.Operator.ToLowerInvariant() switch
        {
            "older_than" => $"older_than(\"{escaped}\")",
            "newer_than" => $"newer_than(\"{escaped}\")",
            _ => $"{durc.Operator}(\"{escaped}\")"
        };
    }

    private static string FormatAndCondition(AndCondition ac, int indentLevel, LuaSerializerOptions options)
    {
        if (ac.Conditions.Count == 0) return string.Empty;
        if (ac.Conditions.Count == 1) return FormatCondition(ac.Conditions[0], indentLevel, options);

        var childIndent = Indent(indentLevel + 1, options);
        var parentIndent = Indent(indentLevel, options);
        var childStrings = ac.Conditions.Select(c => $"{childIndent}{FormatCondition(c, indentLevel + 1, options)}");

        return $"And(\n{string.Join(",\n", childStrings)}\n{parentIndent})";
    }

    private static string FormatOrCondition(OrCondition oc, int indentLevel, LuaSerializerOptions options)
    {
        if (oc.Conditions.Count == 0) return string.Empty;
        if (oc.Conditions.Count == 1) return FormatCondition(oc.Conditions[0], indentLevel, options);

        var childIndent = Indent(indentLevel + 1, options);
        var parentIndent = Indent(indentLevel, options);
        var childStrings = oc.Conditions.Select(c => $"{childIndent}{FormatCondition(c, indentLevel + 1, options)}");

        return $"Or(\n{string.Join(",\n", childStrings)}\n{parentIndent})";
    }

    public static string FormatAction(
        GmailAction action,
        LuaSerializerOptions options,
        IEnumerable<GmailLabel>? knownLabels = null)
    {
        var effectiveLabels = knownLabels ?? options.KnownLabels;
        var idToName = effectiveLabels?
            .Where(l => !string.IsNullOrEmpty(l.Id) && !string.IsNullOrEmpty(l.Name))
            .ToDictionary(l => l.Id!, l => l.Name, StringComparer.OrdinalIgnoreCase);

        var items = new List<string>();

        // Prefer concise DSL commands for system label additions/removals
        if (action.IsArchive) items.Add("archive");
        if (action.IsMarkUnread) items.Add("mark_read");
        if (action.IsStarred) items.Add("star");
        if (action.IsDelete) items.Add("delete");
        if (action.IsImportant) items.Add("mark_important");

        if (action.Category != null)
        {
            string cat = FormatCategoryAction(action.Category);
            items.Add($"add_category(\"{cat}\")");
        }

        // Custom labels to add: resolve ID to human-readable Name if known
        foreach (var cl in action.CustomLabels)
        {
            string labelName = (idToName != null && idToName.TryGetValue(cl, out var resolved)) ? resolved : cl;
            items.Add($"add_label(\"{EscapeLuaString(labelName)}\")");
        }

        // Custom labels to remove: resolve ID to human-readable Name if known
        foreach (var rl in action.CustomRemoveLabels)
        {
            string labelName = (idToName != null && idToName.TryGetValue(rl, out var resolved)) ? resolved : rl;
            items.Add($"remove_label(\"{EscapeLuaString(labelName)}\")");
        }

        if (!string.IsNullOrWhiteSpace(action.Forward))
        {
            items.Add($"forward_message(\"{EscapeLuaString(action.Forward)}\")");
        }

        return items.Count == 0 ? "actions()" : $"actions({string.Join(", ", items)})";
    }

    private static string FormatCategoryAction(string category)
    {
        return category.ToUpperInvariant() switch
        {
            SystemLabels.CategoryPersonal => "Primary",
            SystemLabels.CategoryPurchases => "Purchases",
            SystemLabels.CategorySocial => "Social",
            SystemLabels.CategoryUpdates => "Updates",
            SystemLabels.CategoryForums => "Forums",
            SystemLabels.CategoryPromotions => "Promotions",
            _ => category.StartsWith("CATEGORY_", StringComparison.OrdinalIgnoreCase)
                ? category[9..].ToLowerInvariant()
                : category
        };
    }

    private static string FormatColor(string colorHex, LuaSerializerOptions options)
    {
        if (string.IsNullOrWhiteSpace(colorHex)) return "\"\"";

        if (options.PreferColorAliases)
        {
            if (string.Equals(colorHex, "#ffffff", StringComparison.OrdinalIgnoreCase)) return "\"white\"";
            if (string.Equals(colorHex, "#000000", StringComparison.OrdinalIgnoreCase)) return "\"black\"";
        }

        return $"\"{colorHex.ToLowerInvariant()}\"";
    }

    private static string Indent(int level, LuaSerializerOptions options) =>
        level <= 0 ? string.Empty : new string(' ', level * options.IndentSpaces);

    public static string EscapeLuaString(string? value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        var sb = new StringBuilder(value.Length + 4);
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\': sb.Append(@"\\"); break;
                case '"': sb.Append(@"\"""); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                case '\t': sb.Append(@"\t"); break;
                default:
                    if (char.IsControl(c))
                    {
                        sb.Append($"\\{(int)c:D3}");
                    }
                    else
                    {
                        sb.Append(c);
                    }
                    break;
            }
        }
        return sb.ToString();
    }
}
