<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LuaCSharp" Version="0.5.6" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="VitaCernita.Core.Queries" />
    <Using Include="VitaCernita.Core.Queries.Validation" />
    <Using Include="VitaCernita.Core.Labels" />
    <Using Include="VitaCernita.Core.Labels.Validation" />
  </ItemGroup>

</Project>
