<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="LuaCSharp" Version="0.5.6" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="VitaCernita.Core.Queries" />
    <Using Include="VitaCernita.Core.Queries.Validation" />
    <Using Include="VitaCernita.Core.Labels" />
    <Using Include="VitaCernita.Core.Labels.Validation" />
    <Using Include="VitaCernita.Core.Diffing" />
    <Using Include="VitaCernita.Core.Diffing.Labels" />
    <Using Include="VitaCernita.Core.Diffing.Filters" />
    <Using Include="VitaCernita.Core.Diffing.AutoReply" />
    <Using Include="VitaCernita.Core.Operations" />
    <Using Include="VitaCernita.Core.Operations.Labels" />
    <Using Include="VitaCernita.Core.Operations.Filters" />
    <Using Include="VitaCernita.Core.Operations.AutoReply" />
    <Using Include="VitaCernita.Core.Operations.Translators" />
    <Using Include="VitaCernita.Core.Api" />
    <Using Include="VitaCernita.Core.Api.Auth" />
    <Using Include="VitaCernita.Core.Api.Fakes" />
    <Using Include="VitaCernita.Core.Sources" />
  </ItemGroup>

</Project>
